export const ErrorCode = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  UNAUTHORIZED: "UNAUTHORIZED",
  CSRF_FAILED: "CSRF_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  CARD_NOT_FOUND: "CARD_NOT_FOUND",
  CARD_INACTIVE: "CARD_INACTIVE",
  CARD_NUMBER_TAKEN: "CARD_NUMBER_TAKEN",
  PERIOD_NOT_FOUND: "PERIOD_NOT_FOUND",
  PERIOD_EXPIRED: "PERIOD_EXPIRED",
  MEMBER_NOT_FOUND: "MEMBER_NOT_FOUND",
  MEMBER_INELIGIBLE: "MEMBER_INELIGIBLE",
  MEMBER_LIMIT_REACHED: "MEMBER_LIMIT_REACHED",
  QUOTA_EXHAUSTED: "QUOTA_EXHAUSTED",
  RENEWAL_NOT_ELIGIBLE: "RENEWAL_NOT_ELIGIBLE",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
  USAGE_NOT_FOUND: "USAGE_NOT_FOUND",
  USAGE_ALREADY_VOIDED: "USAGE_ALREADY_VOIDED",
  OFFER_NOT_FOUND: "OFFER_NOT_FOUND",
} as const;

export type ErrorCodeName = (typeof ErrorCode)[keyof typeof ErrorCode];

const STATUS_BY_CODE: Record<ErrorCodeName, number> = {
  VALIDATION_ERROR: 400,
  UNAUTHENTICATED: 401,
  UNAUTHORIZED: 403,
  CSRF_FAILED: 403,
  RATE_LIMITED: 429,
  INVALID_CREDENTIALS: 401,
  CARD_NOT_FOUND: 404,
  CARD_INACTIVE: 409,
  CARD_NUMBER_TAKEN: 409,
  PERIOD_NOT_FOUND: 404,
  PERIOD_EXPIRED: 409,
  MEMBER_NOT_FOUND: 404,
  MEMBER_INELIGIBLE: 409,
  MEMBER_LIMIT_REACHED: 409,
  QUOTA_EXHAUSTED: 409,
  RENEWAL_NOT_ELIGIBLE: 409,
  IDEMPOTENCY_CONFLICT: 409,
  USAGE_NOT_FOUND: 404,
  USAGE_ALREADY_VOIDED: 409,
  OFFER_NOT_FOUND: 404,
};

export class DomainError extends Error {
  readonly code: ErrorCodeName;
  readonly status: number;
  readonly details?: unknown;

  constructor(code: ErrorCodeName, message?: string, details?: unknown) {
    super(message ?? code);
    this.name = "DomainError";
    this.code = code;
    this.status = STATUS_BY_CODE[code];
    this.details = details;
  }
}
